export const COORDINATE_SELECTED = 'COORDINATE_SELECTED';
export const TITLE_ADDED = 'TITLE_ADDED';
export const DESCRIPTION_ADDED = 'DESCRIPTION_ADDED';
export const IMAGE_ADDED = 'IMAGE_ADDED';
export const ADD_TASK = 'ADD_TASK';

export const INCIDENT_SELECTED = 'INCIDENT_SELECTED';
export const INCIDENT_CREATED = 'INCIDENT_CREATED';